### ISSUE TITLE
Changes to batch_config.yaml

### ISSUE THREAD

**Issue by mgkahn** [stanfordmed/n3c-spark-exporter#4]
More a question than an issue.....
Colorado participated in N3C Data Expansion, which requires including NOTE, NOTE_NLP, and VISIT_DETAIL tables as part of our payload. The extracted tables and associated SQL are described in the config/batch_config.yaml file. But Line #1 in this file has a all-caps "DO NOT CHANGE" warning. Is this file autogenerated such that my additions of the above three tables will be overwritten?

I'm working on a new "Colorado" branch for my changes.

**Comment by smitalimaye** [comment]
You are right, if you need to have more tables exported, you need to add SQLs here and add those additional 3 cdm tables to this list - https://github.com/stanfordmed/n3c-spark-exporter/blob/main/src/n3c_spark_extractor/config/batch_config.yaml#L22

And you should be set is what I think. If you could create a PR, I can take a look and you can be unblocked.

Permanent solution - we have to move - 
https://github.com/stanfordmed/n3c-spark-exporter/blob/main/src/n3c_spark_extractor/config/batch_config.yaml#L22
to 
https://github.com/stanfordmed/n3c-spark-exporter/blob/main/config_example.yaml 
so that it can work for any list of tables. And there is no need to build the module for the table list change. We can make that change in next version.

Hope this helps.

**Comment by smitalimaye** [comment]
I have created https://github.com/stanfordmed/n3c-spark-exporter/pull/6 for adding support for additional tables. Please see the README file for configuration change required.
Could you please review and make sure if that works for you? LMK if you have any questions.

**Comment by smitalimaye** [comment]
This is fixed in 1.2.0
